---
# Source: eth2-teku/templates/validator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-client-1
  namespace: teku
  labels:
    app: validator-client-1
spec:
  selector:
    matchLabels:
      app: validator-client-1
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-client-1
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo "Wait for 780 second(s) for extra slashing protection!" && sleep 780']
      containers:
      - name: validator-client-1
        image: "index.docker.io/consensys/teku:22.4.0"
        args:
        - vc
        - --network=prater
        - --beacon-node-api-endpoint=http://beacon-service.teku.svc.cluster.local:5051
        - --data-validator-path=/data/teku/validator-client-1
        - --validator-keys=/data/teku/validator-keys-1:/data/teku/validator-key-passwords-1
        - --validators-graffiti="eth2 x k8s"
        - --metrics-enabled=true
        - --metrics-interface=0.0.0.0
        - --log-destination=CONSOLE
        ports:
        - containerPort: 8008
          protocol: TCP
          name: metrics
        volumeMounts:        
        - name: teku-local-storage
          mountPath: /.local/share/teku
          readOnly: false
        - name: teku-validator-storage
          mountPath: /data/teku/validator-client-1
          readOnly: false
        - name: teku-passwords-storage
          mountPath: /data/teku/validator-key-passwords-1
          readOnly: true
        - name: teku-keys-storage
          mountPath: /data/teku/validator-keys-1
          readOnly: false
      volumes:      
      - name: teku-local-storage
        hostPath:
          path: /data/teku/local
      - name: teku-validator-storage
        hostPath:
          path: /data/teku/validator-client-1
      - name: teku-passwords-storage
        hostPath:
          path: /data/teku/validator-key-passwords-1
      - name: teku-keys-storage
        hostPath:
          path: /data/teku/validator-keys-1
      securityContext:
        runAsGroup: 2000
        runAsUser: 1001
      serviceAccountName: validator-client
      restartPolicy: Always
