---
# Source: eth2-lighthouse/templates/beacon-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon
  namespace: lighthouse
  labels:
    app: beacon
spec:
  selector:
    matchLabels:
      app: beacon
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: beacon
    spec:
      containers:
      - name: beacon
        image: "index.docker.io/sigp/lighthouse:v2.2.1"
        args:
        - lighthouse
        - --network=prater
        - bn
        - --staking
        - --http-address=0.0.0.0
        - --eth1-endpoints=http://127.0.0.1:8545,http://127.0.0.1:8546
        - --datadir=/data/lighthouse/beacon
        - --metrics
        - --metrics-address=0.0.0.0
        ports:
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - containerPort: 9000
          hostPort: 9000
          protocol: UDP
        - containerPort: 5052
          protocol: TCP
        - containerPort: 5054
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: beacon-storage
          mountPath: /data/lighthouse/beacon
      volumes:
      - name: beacon-storage
        nfs:
          path: /data/lighthouse
          server: 172.20.10.10
          readOnly: false
      securityContext:
        runAsGroup: 2000
        runAsUser: 1001
      serviceAccountName: beacon
      restartPolicy: Always
