---
# Source: eth2-lighthouse/templates/validator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-client-1
  namespace: lighthouse
  labels:
    app: validator-client-1
spec:
  selector:
    matchLabels:
      app: validator-client-1
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-client-1
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo "Wait for 780 second(s) for extra slashing protection!" && sleep 780']
      containers:
      - name: validator-client-1
        image: "index.docker.io/sigp/lighthouse:v2.2.1"
        args:
        - lighthouse
        - --network=prater
        - vc
        - --beacon-nodes=http://beacon-service.lighthouse.svc.cluster.local:5052
        - --datadir=/data/lighthouse/validator-client-1
        - --graffiti="eth2 x k8s"
        - --metrics
        - --metrics-address=0.0.0.0
        ports:
        - containerPort: 5064
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: validator-client-storage
          mountPath: /data/lighthouse/validator-client-1
          readOnly: false
      volumes:
      - name: validator-client-storage
        nfs:
          path: /data/lighthouse/validator-client-1
          server: 172.20.10.10
          readOnly: false
      securityContext:
        runAsGroup: 2000
        runAsUser: 1001
      serviceAccountName: validator-client
      restartPolicy: Always
