---
# Source: eth2-teku/templates/beacon-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon
  namespace: teku
  labels:
    app: beacon
spec:
  selector:
    matchLabels:
      app: beacon
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: beacon
    spec:
      containers:
      - name: beacon
        image: "index.docker.io/consensys/teku:22.4.0"
        args:
        - --network=prater
        - --p2p-port=9000
        - --rest-api-enabled
        - --rest-api-host-allowlist=*
        - --eth1-endpoints=http://127.0.0.1:8545,http://127.0.0.1:8546,http://127.0.0.1:8547
        - --data-beacon-path=/data/teku/beacon
        - --log-destination=CONSOLE
        - --metrics-enabled=true
        - --metrics-interface=0.0.0.0
        ports:
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - containerPort: 9000
          hostPort: 9000
          protocol: UDP
        - containerPort: 5051
          protocol: TCP
          name: rest-api
        - containerPort: 8008
          protocol: TCP
          name: metrics
        volumeMounts:        
        - name: teku-beacon-storage
          mountPath: /data/teku/beacon
          readOnly: false
        - name: teku-local-storage
          mountPath: /.local/share/teku
          readOnly: false
        livenessProbe:
          httpGet:
            path: /teku/v1/admin/liveness
            port: rest-api
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /eth/v1/node/health
            port: rest-api
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 1
      volumes:      
      - name: teku-beacon-storage
        nfs:
          path: /data/teku/beacon
          server: 172.20.10.10
          readOnly: false
      - name: teku-local-storage
        nfs:
          path: /data/teku/local
          server: 172.20.10.10
          readOnly: false
      securityContext:
        runAsGroup: 2000
        runAsUser: 1001
      serviceAccountName: beacon
      restartPolicy: Always
