---
# Source: eth2-prysm/templates/validator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-client-1
  namespace: prysm
  labels:
    app: validator-client-1
spec:
  selector:
    matchLabels:
      app: validator-client-1
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-client-1
      annotations:
        checksum/config: 738e8a2194c6076100be9e45ff68d964c8d6d13290087cdc2ff2f4e0e37d24c5
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo "Wait for 780 second(s) for extra slashing protection!" && sleep 780']
      containers:
      - name: validator-client-1
        image: "gcr.io/prysmaticlabs/prysm/validator:v2.0.6"
        args:
        - --prater
        - --beacon-rpc-provider=beacon-service.prysm.svc.cluster.local:4000
        - --datadir=/data/prysm/validator-client-1
        - --wallet-dir=/data/prysm/wallet-1
        - --wallet-password-file=/data/prysm/password/wallet-pwd.txt
        - --monitoring-host=0.0.0.0
        - --graffiti="eth2 x k8s"
        - --accept-terms-of-use
        ports:
        - containerPort: 8081
          protocol: TCP
          name: metrics
        volumeMounts:        
        - name: prysm-validator-storage
          mountPath: /data/prysm/validator-client-1
          readOnly: false
        - name: prysm-wallet-storage
          mountPath: /data/prysm/wallet-1
          readOnly: true
        - name: wallet-password
          mountPath: /data/prysm/password
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
      volumes:      
      - name: prysm-validator-storage
        nfs:
          path: /data/prysm/validator-client-1
          server: 172.20.10.10
          readOnly: false
      - name: prysm-wallet-storage
        nfs:
          path: /data/prysm/wallet-1
          server: 172.20.10.10
          readOnly: true
      - name: wallet-password
        secret:
          secretName: wallet-password-1
          items:
          - key: password
            path: wallet-pwd.txt
      securityContext:
        runAsGroup: 2000
        runAsUser: 1001
      serviceAccountName: validator-client
      restartPolicy: Always
