---
# Source: eth2-nimbus/templates/nimbus-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-1
  namespace: nimbus
  labels:
    app: nimbus-1
spec:
  selector:
    matchLabels:
      app: nimbus-1
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: nimbus-1
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo Wait for 780 seconds for extra slashing protection! && sleep 780']
      containers:
      - name: nimbus
        image: "index.docker.io/statusim/nimbus-eth2:amd64-v22.4.0"
        args:
        - --network=prater
        - --non-interactive
        - --tcp-port=9000
        - --udp-port=9000
        - --data-dir=/data/nimbus/beacon-1
        - --validators-dir=/data/nimbus/validators-1
        - --secrets-dir=/data/nimbus/secrets-1
        - --metrics-address=0.0.0.0
        - --metrics
        - --web3-url=ws://127.0.0.1:8545
        - --web3-url=ws://127.0.0.1:8546
        - --web3-url=ws://127.0.0.1:8547
        - --graffiti="eth2 x k8s"
        ports:
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - containerPort: 9000
          hostPort: 9000
          protocol: UDP
        - containerPort: 8008
          protocol: TCP
          name: metrics
        volumeMounts:        
        - name: nimbus-beacon-storage
          mountPath: /data/nimbus/beacon-1
          readOnly: false
        - name: nimbus-secrets-storage
          mountPath: /data/nimbus/secrets-1
          readOnly: true
        - name: nimbus-validators-storage
          mountPath: /data/nimbus/validators-1
          readOnly: false
      volumes:      
      - name: nimbus-beacon-storage
        hostPath:
          path: /data/nimbus/beacon-1
      - name: nimbus-secrets-storage
        hostPath:
          path: /data/nimbus/secrets-1
      - name: nimbus-validators-storage
        hostPath:
          path: /data/nimbus/validators-1
      securityContext:
        runAsGroup: 2000
        runAsUser: 1001
      serviceAccountName: nimbus
      restartPolicy: Always
